# Generated by Django 5.1.3 on 2024-11-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('published_year', models.IntegerField()),
                ('edition', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subjects', models.CharField(max_length=255)),
                ('image', models.ImageField(default='BookHub/bookapp/src/Images/No_Cover.jpg', upload_to='image/')),
            ],
        ),
    ]
